# Generated by Django 2.2.6 on 2019-10-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
                ('comment_contents', models.CharField(max_length=200)),
                ('comment_writer', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postapp.Post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
